image: python:alpine

before_script:
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs
  ## Add your custom theme if not inside a theme_dir
  ## (https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
  - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mkdocs-material

pages:
  script:
  - mkdocs build
  - du [-m]site
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master