# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Frytea Material Docs
site_description: Technology, Android, CI/CD, Git, Cloud Company, Gis, Web, PipeLine and so on.
site_author: Tianlun Song
site_url: https://docs.github.frytea.com

# Repository
repo_name: songtianlun/frytea-docs
repo_url: https://github.com/songtianlun/frytea-docs
edit_uri: "https://github.com/songtianlun/frytea-docs/edit/master/docs"

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 frytea'

# Configuration
theme:
  name: null
  custom_dir: 'material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: Brown
    accent: 'Deep Orange'
  font:
    text: Cormorant
    code: Cormorant Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search
      language: 'en, zh'
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: globe
      link: http://www.frytea.com
    - type: github-alt
      link: https://github.com/songtianlun
    - type: twitter
      link: https://twitter.com/tianlun_song
    - type: linkedin
      link: https://linkedin.com/in/songtianlun

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Material-Docs: index.md
  - Program-OS:
    - Linux-Command: Program-OS/Linux-Command
  - Dev-OS:
    - Wiki-Docs: Dev-OS/Wiki-Docs/index.md
  - Projects: Projects/index.md
  - Author's notes: authors-notes.md
  - Contributing: contributing.md
  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
